---
packages:
  - .dev/automation/mcp-server
  - apps/**
  - ui/**
  - platform/**
  - resources/**
  - "!platform/n00-frontiers/**/examples/**"
  - "!**/templates/**"
  - "!**/cookiecutter/**"

# Workspace settings that help centralize installs
sharedWorkspaceLockfile: true
linkWorkspacePackages: true
includeWorkspaceRoot: true
resolvePeersFromWorkspaceRoot: true
hoist: true
hoistWorkspacePackages: true
hoistPattern:
  - "*"
preferWorkspacePackages: true
saveWorkspaceProtocol: rolling
nodeLinker: hoisted
onlyBuiltDependencies:
  [
    "@swc/core",
    "aws-sdk",
    "better-sqlite3",
    "core-js",
    "esbuild",
    "protobufjs",
    "sharp",
    "unrs-resolver",
    "workerd",
  ]
