---
packages:
  - .dev/automation/mcp-server
  - ui/**
  - apps/**
  - packages/**
  - stuff/**

# Workspace settings that help centralize installs
sharedWorkspaceLockfile: true
linkWorkspacePackages: true
includeWorkspaceRoot: true
resolvePeersFromWorkspaceRoot: true
hoist: true
hoistWorkspacePackages: true
hoistPattern:
  - "*"
preferWorkspacePackages: true
saveWorkspaceProtocol: rolling
nodeLinker: hoisted
