---
packages:
  - .dev/automation/mcp-server
  - apps/**
  - ui/**
  - platform/**
  - resources/**
  - "!**/templates/**"
  - "!**/cookiecutter/**"

# Workspace settings that help centralize installs
sharedWorkspaceLockfile: true
linkWorkspacePackages: true
includeWorkspaceRoot: true
resolvePeersFromWorkspaceRoot: true
hoist: true
hoistWorkspacePackages: true
hoistPattern:
  - "*"
preferWorkspacePackages: true
saveWorkspaceProtocol: rolling
nodeLinker: hoisted
