#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
DEFAULT_REQ_FULL="$ROOT_DIR/requirements.workspace.txt"
DEFAULT_LOCK_FULL="$ROOT_DIR/requirements.workspace.lock"
DEFAULT_REQ_MIN="$ROOT_DIR/requirements.workspace.min.txt"
DEFAULT_LOCK_MIN="$ROOT_DIR/requirements.workspace.min.lock"

usage() {
	cat <<'EOF'
refresh-python-lock.sh [--full] [--minimal] [--check]
  --full      refresh/check full workspace lock (includes n00-frontiers)
  --minimal   refresh/check minimal workspace lock (default if none specified)
  --check     verify locks are up to date (no rewrite)
If no scope is provided, both locks are processed.
EOF
}

SCOPE_FULL=false
SCOPE_MIN=false
CHECK=false
while [[ $# -gt 0 ]]; do
	case "$1" in
	--full) SCOPE_FULL=true ;;
	--minimal) SCOPE_MIN=true ;;
	--check) CHECK=true ;;
	-h | --help)
		usage
		exit 0
		;;
	*)
		echo "Unknown flag: $1" >&2
		usage
		exit 1
		;;
	esac
	shift
done

if ! $SCOPE_FULL && ! $SCOPE_MIN; then
	SCOPE_FULL=true
	SCOPE_MIN=true
fi

if ! command -v uv >/dev/null 2>&1; then
	echo "uv is required. Install via: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
	exit 1
fi

UV_COMPILE_ARGS=${UV_COMPILE_ARGS:---prerelease=allow}
CONSTRAINTS_FILE="${ROOT_DIR}/workspace-constraints.txt"
if [[ -f ${CONSTRAINTS_FILE} ]]; then
	UV_COMPILE_ARGS="${UV_COMPILE_ARGS} --constraint ${CONSTRAINTS_FILE}"
fi

rewrite_header() {
	local file="$1"
	local command="$2"
	local tmp_file
	tmp_file=$(mktemp)
	{
		printf '# This file was autogenerated by uv via the following command:\n'
		printf '#    %s\n' "$command"
		tail -n +3 "$file"
	} >"$tmp_file"
	mv "$tmp_file" "$file"
}

process_lock() {
	local req="$1" lock="$2"
	local label="$3"
	if [[ ! -f $req ]]; then
		echo "requirements file not found: $req" >&2
		return 1
	fi
	local req_display lock_display custom_command
	req_display=${req#"$ROOT_DIR/"}
	if [[ $req_display == "$req" ]]; then
		req_display="$req"
	fi
	lock_display=${lock#"$ROOT_DIR/"}
	if [[ $lock_display == "$lock" ]]; then
		lock_display="$lock"
	fi
	custom_command="uv pip compile $UV_COMPILE_ARGS $req_display -o $lock_display"
	if $CHECK; then
		tmp=$(mktemp)
		trap 'rm -f "$tmp"' RETURN
		uv pip compile $UV_COMPILE_ARGS "$req" -o "$tmp"
		rewrite_header "$tmp" "$custom_command"
		if ! diff -u "$lock" "$tmp" >/dev/null 2>&1; then
			echo "$label is out of date" >&2
			diff -u "$lock" "$tmp" || true
			return 1
		fi
		echo "$label up to date"
	else
		echo "Rebuilding $label with uv..."
		uv pip compile $UV_COMPILE_ARGS "$req" -o "$lock"
		rewrite_header "$lock" "$custom_command"
		printf "Updated %s -> %s\n" "$req" "$lock"
	fi
}

STATUS=0
if $SCOPE_MIN; then
	process_lock "$DEFAULT_REQ_MIN" "$DEFAULT_LOCK_MIN" "requirements.workspace.min.lock" || STATUS=$?
fi
if $SCOPE_FULL; then
	process_lock "$DEFAULT_REQ_FULL" "$DEFAULT_LOCK_FULL" "requirements.workspace.lock" || STATUS=$?
fi

exit $STATUS
