#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
ARTIFACTS_DIR="$ROOT/.dev/automation/artifacts/ai-workflows/architecture-diagrams"
SCRIPTS_DIR="$ROOT/.dev/automation/scripts"
RECORD_SCRIPT="$SCRIPTS_DIR/record-capability-run.py"

# Enhanced error handling
trap 'echo "❌ Architecture phase failed at line $LINENO" >&2' ERR

mkdir -p "$ARTIFACTS_DIR"

log() {
  echo "[🏗️  ai-architecture] $1"
}

error() {
  echo "[❌ ai-architecture] ERROR: $1" >&2
  exit 1
}

success() {
  echo "[✅ ai-architecture] $1"
}

# Progress indicator
show_progress() {
  local step=$1
  local total=$2
  local desc=$3
  echo "[📊 Progress: $step/$total] $desc"
}

log "🚀 Starting AI-Assisted Architecture & Design"
log "🎯 Why this split? Grok for diagrams/reasoning; Codex for code skeletons."

STARTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

show_progress 1 4 "Initializing architecture phase"

echo
echo "🏗️  Architecture & Design Phase"
echo "==============================="
echo
echo "Steps:"
echo "1. 🏛️  Define system architecture"

# Enhanced architecture gathering
echo "   What type of application?"
echo "   • Web App (frontend/backend)"
echo "   • API/Service"
echo "   • Mobile App"
echo "   • Desktop App"
echo "   • Microservices"
read -p "Application type: " APP_TYPE || error "Application type required"

echo "2. 🔧 Define tech stack"
read -p "Frontend technologies: " FRONTEND_STACK || FRONTEND_STACK="React, TypeScript"
read -p "Backend technologies: " BACKEND_STACK || BACKEND_STACK="Node.js, Express"
read -p "Database: " DATABASE || DATABASE="PostgreSQL"
read -p "Infrastructure: " INFRA || INFRA="AWS/Docker"

show_progress 2 4 "Analyzing architecture requirements"

echo "3. 📊 Define data flow"
read -p "Key data entities: " DATA_ENTITIES || DATA_ENTITIES="Users, Projects, Tasks"
read -p "API endpoints needed: " API_ENDPOINTS || API_ENDPOINTS="CRUD operations"

echo "4. 🎨 Design system components"
read -p "UI components needed: " UI_COMPONENTS || UI_COMPONENTS="Forms, Tables, Navigation"

show_progress 3 4 "Generating architecture diagram"

# Generate Mermaid diagram
DIAGRAM_FILE="$ARTIFACTS_DIR/diagram-$(date +%Y%m%d-%H%M%S).md"

cat > "$DIAGRAM_FILE" << EOF
# Architecture Diagram - $APP_TYPE

## 🏛️ System Overview

\`\`\`mermaid
graph TB
    A[Client] --> B[API Gateway]
    B --> C[Authentication Service]
    B --> D[Business Logic Service]
    D --> E[Database]
    D --> F[External APIs]

    subgraph "Frontend Layer"
        A
    end

    subgraph "Backend Layer"
        C
        D
    end

    subgraph "Data Layer"
        E
    end

    subgraph "External Services"
        F
    end

    style A fill:#e1f5fe
    style C fill:#f3e5f5
    style D fill:#e8f5e8
    style E fill:#fff3e0
\`\`\`

## 📋 Technology Stack

### Frontend
- **Framework**: $FRONTEND_STACK
- **State Management**: Context/Redux/Zustand
- **Styling**: Tailwind CSS
- **Testing**: Jest + React Testing Library

### Backend
- **Runtime**: $BACKEND_STACK
- **Authentication**: JWT/OAuth
- **Validation**: Joi/Yup
- **Testing**: Jest + Supertest

### Database
- **Primary**: $DATABASE
- **ORM**: Prisma/TypeORM
- **Migration**: Automated
- **Backup**: Daily automated

### Infrastructure
- **Platform**: $INFRA
- **Containerization**: Docker
- **CI/CD**: GitHub Actions
- **Monitoring**: Application Insights

## 🔄 Data Flow

1. **User Request** → API Gateway
2. **Authentication** → JWT Validation
3. **Business Logic** → Service Layer
4. **Data Access** → Repository Pattern
5. **Response** → Formatted JSON

## 🎯 Key Components

### Core Entities
$DATA_ENTITIES

### API Endpoints
$API_ENDPOINTS

### UI Components
$UI_COMPONENTS

## 🚀 Deployment Architecture

\`\`\`mermaid
graph LR
    A[Git Push] --> B[CI Pipeline]
    B --> C[Test Stage]
    C --> D[Build Stage]
    D --> E[Deploy Stage]
    E --> F[Production]

    subgraph "CI/CD Pipeline"
        B
        C
        D
        E
    end
\`\`\`

## ⚡ Performance Considerations

- **Caching**: Redis for session/API data
- **CDN**: CloudFront for static assets
- **Database**: Connection pooling, indexing
- **Monitoring**: Response times, error rates

## 🔒 Security Measures

- **Authentication**: Multi-factor authentication
- **Authorization**: Role-based access control
- **Data**: Encryption at rest/transit
- **API**: Rate limiting, input validation
- **Infrastructure**: VPC, security groups

---
*Generated by AI Workflow Architecture Phase*
EOF

success "Architecture diagram saved to $DIAGRAM_FILE"

show_progress 4 4 "Recording capability run"

echo
echo "🎉 Architecture & Design Phase Complete!"
echo "========================================"
echo
echo "📄 Generated: $DIAGRAM_FILE"
echo "🔄 Next: Run core-coding.sh"
echo
echo "💡 Pro Enhancements:"
echo "   • Grok 4 for 512k repo-wide designs"
echo "   • Vertex AI for enterprise governance"
echo
echo "🤝 Involve Others:"
echo "   • Claude for acceptance criteria"
echo "   • Llama 3.x for private design reviews"
echo
echo "🎨 Fit for Python/TS:"
echo "   • TypeScript for type safety"
echo "   • Python for rapid prototyping"

COMPLETED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -f "$RECORD_SCRIPT" ]; then
    python3 "$RECORD_SCRIPT" \
        --capability "ai.workflow.architecture" \
        --status "succeeded" \
        --summary "Architecture diagram generated for $APP_TYPE" \
        --started "$STARTED_AT" \
        --completed "$COMPLETED_AT" \
        --metadata "{\"diagram\": \"$DIAGRAM_FILE\"}"
fi

success "Architecture & Design completed ✅"
    A[Client] --> B[API]
    B --> C[Database]
Skeletons: "$SKELETONS"
EOF

log "Diagram saved to $DIAGRAM_FILE"

echo "Pro Enhancements: Grok 4 for 512k repo-wide designs; Codex fine-tunes."
echo "Fit for Python/TS: Codex for TS types; Grok for cross-lang integration."
echo "Output: Diagrams, stub files. Use Grok's sandbox for early testing."

COMPLETED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -f "$RECORD_SCRIPT" ]; then
    python3 "$RECORD_SCRIPT" \
        --capability "ai.workflow.architecture" \
        --status "succeeded" \
        --summary "Architecture diagram generated for $ARCH_FOCUS" \
        --started "$STARTED_AT" \
        --completed "$COMPLETED_AT" \
        --metadata "{\"diagram\": \"$DIAGRAM_FILE\"}"
fi

log "Architecture & Design completed."