#!/bin/bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
ARTIFACTS_DIR="$ROOT/.dev/automation/artifacts/ai-workflows/planning-specs"
SCRIPTS_DIR="$ROOT/.dev/automation/scripts"
RECORD_SCRIPT="$SCRIPTS_DIR/record-capability-run.py"

# Enhanced error handling
trap 'echo "❌ Planning phase failed at line $LINENO" >&2' ERR

mkdir -p "$ARTIFACTS_DIR"

log() {
	echo "[🤖 ai-planning] $1"
}

error() {
	echo "[❌ ai-planning] ERROR: $1" >&2
	exit 1
}

success() {
	echo "[✅ ai-planning] $1"
}

# Progress indicator
show_progress() {
	local step=$1
	local total=$2
	local desc=$3
	echo "[📊 Progress: $step/$total] $desc"
}

log "🚀 Starting AI-Assisted Planning & Research"
log "🎯 Why Grok? Handles ambiguity, research, and synthesis best."

STARTED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

show_progress 1 4 "Initializing planning phase"

echo
echo "📋 Planning & Research Phase"
echo "============================"
echo
echo "Steps:"
echo "1. 📝 Describe your project."
read -p "Project description: " PROJECT_DESC || error "Project description required"

echo "2. 🔍 Grok researches dependencies/trends."
# Check for API key
if [ -f "$ROOT/.secrets/grok-api-key" ]; then
	log "🔑 Grok API key found - research enabled"
	RESEARCH_NOTES="API research results here"
else
	log "⚠️  No Grok API key found. Manual research recommended."
	RESEARCH_NOTES="Manual research required - add .secrets/grok-api-key for automated research"
fi

show_progress 2 4 "Gathering project requirements"

# Enhanced project analysis
echo "3. 🎯 Analyzing project scope..."
read -p "Target platforms (web,mobile,desktop,api): " TARGET_PLATFORMS || TARGET_PLATFORMS="web"
read -p "Tech stack preferences: " TECH_STACK || TECH_STACK="TypeScript, React, Node.js"
read -p "Timeline estimate: " TIMELINE || TIMELINE="3-6 months"
read -p "Team size: " TEAM_SIZE || TEAM_SIZE="1-3 developers"

show_progress 3 4 "Generating project specification"

# Create comprehensive spec
SPEC_FILE="$ARTIFACTS_DIR/spec-$(date +%Y%m%d-%H%M%S).md"

cat >"$SPEC_FILE" <<EOF
# AI-Assisted Development Project Specification

## 📋 Project Overview
**Description**: $PROJECT_DESC
**Generated**: $(date)
**Phase**: Planning & Research

## 🎯 Project Scope
- **Platforms**: $TARGET_PLATFORMS
- **Tech Stack**: $TECH_STACK
- **Timeline**: $TIMELINE
- **Team Size**: $TEAM_SIZE

## 🔍 Research Findings
$RESEARCH_NOTES

## 📊 Recommendations
**Primary AI**: Grok (xAI)
- Best for: Planning, research, synthesis
- Strengths: Large context, real-time tools

**Secondary AI**: GitHub Copilot
- Best for: Implementation, code generation
- Integration: VS Code native

## 🏗️ Architecture Considerations
- **Scalability**: Consider microservices if timeline > 6 months
- **Security**: Implement auth from day one
- **Performance**: Choose frameworks with good async support

## ⚠️ Risks & Mitigations
- **Timeline Risk**: Break into 2-week sprints
- **Tech Risk**: Prototype key integrations early
- **Team Risk**: Document all decisions

## 📈 Success Metrics
- Code coverage: >80%
- Performance: <2s load times
- Security: Zero critical vulnerabilities
- User satisfaction: >4.5/5

---
*Generated by AI Workflow Planning Phase*
EOF

success "Spec saved to $SPEC_FILE"

show_progress 4 4 "Recording capability run"

echo
echo "🎉 Planning & Research Phase Complete!"
echo "======================================"
echo
echo "📄 Generated: $SPEC_FILE"
echo "🔄 Next: Run architecture-design.sh"
echo
echo "💡 Pro Enhancements:"
echo "   • Use Grok 4's expanded context for detailed plans"
echo "   • Enable 'Heavy' mode for multi-faceted analysis"
echo
echo "🤝 Involve Others:"
echo "   • Query Codex for pseudocode sketches if needed"
echo
echo "🎨 Fit for Python/TS:"
echo "   • Suggests async patterns or type safety"
echo
echo "➡️  Transition:"
echo "   • Export as Markdown; paste into IDE"

COMPLETED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -f "$RECORD_SCRIPT" ]; then
	python3 "$RECORD_SCRIPT" \
		--capability "ai.workflow.planning" \
		--status "succeeded" \
		--summary "Planning spec generated for $PROJECT_DESC" \
		--started "$STARTED_AT" \
		--completed "$COMPLETED_AT" \
		--metadata "{\"spec\": \"$SPEC_FILE\"}"
fi

success "Planning & Research completed ✅"

echo "3. Output: High-level spec, stack recommendations, pitfalls."
SPEC_FILE="$ARTIFACTS_DIR/spec-$(date +%Y%m%d-%H%M%S).md"
cat >"$SPEC_FILE" <<EOF
# Project Spec: $PROJECT_DESC
Generated: $(date)
Research Notes: $RESEARCH_NOTES
Stack Recommendations: Python/TS with FastAPI/React
Pitfalls: Ensure async handling
EOF

log "Spec saved to $SPEC_FILE"

echo "Pro Enhancements: Use Grok 4's expanded context; enable 'Heavy' mode."
echo "Involve Others: Query Codex for pseudocode sketches if needed."
echo "Fit for Python/TS: Suggests async patterns or type safety."
echo "Transition: Export as Markdown; paste into IDE."

COMPLETED_AT=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

if [ -f "$RECORD_SCRIPT" ]; then
	python3 "$RECORD_SCRIPT" \
		--capability "ai.workflow.planning" \
		--status "succeeded" \
		--summary "Planning spec generated for $PROJECT_DESC" \
		--started "$STARTED_AT" \
		--completed "$COMPLETED_AT" \
		--metadata "{\"spec\": \"$SPEC_FILE\"}"
fi

log "Planning & Research completed."
