#!/bin/sh
# ERROR if in detached HEAD state
if ! git symbolic-ref -q HEAD >/dev/null; then
	echo "\033[31mError: You are in a 'detached HEAD' state.\033[0m"
	echo "Please check out a branch before committing."
	exit 1
fi

# Workaround for system permission errors
export TMPDIR="$(pwd)/.tmp"
export XDG_CACHE_HOME="$(pwd)/.cache_local"
mkdir -p "$TMPDIR" "$XDG_CACHE_HOME"

pnpm exec trunk check
pnpm test
